### ISSUE TITLE
Roadmap for BIDS Schema Tools docs

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-specification#1499]
### Your idea

Thanks to @bendhouseart, we are now pushing documentation for the schema tooling to https://bidsschematools.readthedocs.io/en/latest/. This issue is intended to track tasks for improving this site to make it more useful. Please add/edit freely, or comment below.

### Appearance

* [ ] Update theme. [Furo](https://github.com/pradyunsg/furo) is a good, clean theme with dark/light support.
* [ ] Logo. We should have BIDS logos for dark and light themes.

### Content

* [ ] Description of project on landing page. Single-sourcing README for PyPI (https://pypi.org/project/bidsschematools/) and the docs seems like a good idea.
* [ ] Links to other major sites in BIDS.
* [ ] Flesh out API docs. Aim for 100% docstrings of public functions/methods/classes.
* [ ] Add examples, run doctests (if we aren't already)

**Comment by Remi-Gau** [comment]
Should the documentation for the macros be also moved into the official schema doc?

I mean this document
https://github.com/bids-standard/bids-specification/blob/master/macros_doc.md

At least we could symlink it.

WDYT?
